name: client-side

on: [push, pull_request]

jobs:
  test:
    runs-on: //some distribution

    strategy:
      matrix: 
        node-version: []
    steps:
      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start
        
      - name: Run tests
        run: npm test


