name: client-side

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]  

jobs:
  test:

    runs-on: //some distribution

    strategy:
      matrix: 
        node-version: []
    steps:
      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start

      - name: Run tests
        run: npm test


